version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-node
    ports:
      - "9042:9042"   # CQL port
    environment:
      - CASSANDRA_CLUSTER_NAME=SensorCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - cassandra_data:/var/lib/cassandra/data
    networks:
      - cassandra_network

networks:
  cassandra_network:
    driver: bridge

volumes:
  cassandra_data: